set(LIB_FULL_NAME    "${LIB_NAME}")

file(GLOB_RECURSE SOURCES CONFIGURE_DEPENDS src/*.cpp)

add_library(${LIB_FULL_NAME} ${SOURCES})
add_library("Rbel12b-cpplib::${LIB_NAME}" ALIAS ${LIB_FULL_NAME})

target_include_directories(${LIB_FULL_NAME} 
    PUBLIC
        $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
        $<INSTALL_INTERFACE:include>
)

target_include_directories(${LIB_FULL_NAME}
    PRIVATE
        ${CMAKE_CURRENT_SOURCE_DIR}/include/Rbel12b-cpplib/${LIB_NAME}
)

target_compile_features(${LIB_FULL_NAME} PUBLIC cxx_std_17)

install(
    TARGETS ${LIB_FULL_NAME}
    EXPORT ${LIB_TARGETS_NAME}
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
    INCLUDES DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
)

install(
    DIRECTORY include/
    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
)
